name: Feature request
description: Suggest an idea or improvement.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to propose an improvement."
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: "What problem are you trying to solve?"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: "Describe the solution you would like to see."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: "Describe alternatives you have considered."
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: "Links, screenshots, or other context."
    validations:
      required: false
